### PR TITLE
Added species-age visualisation

### PR DESCRIPTION
**Pull request by ruxley**
I duplicated the other visualisation I did as a basis for this one, hopefully it should work! I also used the common `/lib/d3.min.js` rather than include another copy.

### CODE REVIEW

**Comment by makyo** [comment]
Two minors:

* Can you move lodash to the libs dir?  That might show up elsewhere (underscore is notably used in a few other visualizations, and switching to lodash has been on my plate for a while)
* Can you add a line to index /index.html linking to the vis?

Other than that, :+1:!

**Comment by ruxley** [comment]
Good idea with moving lodash. My previous chart used underscore so when I've got time I'll swap that over.

I already added a link to index.html, I just put it beneath my existing chart, I wasn't sure if there was an order to the list but happy to change if so!

**Comment by makyo** [comment]
Oh, whoops, that was the first file, too!  Thanks :)

**Comment by makyo** [comment]
Landing for now, will follow up with lodash branch

**Pull request merged**
